name: cicd

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make ci

  release:
    runs-on: ubuntu-latest
    needs: [ ci ]
    if: github.event_name == 'push' # only run on push to master
    steps:
    - uses: actions/checkout@v3
    - run: git fetch --prune --unshallow --tags
    - run: make release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
